server:
  port: 8081
  servlet:
    context-path: /hotel_reservation_premium

spring:
  profiles:
    active: dev

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

system-user-id: ${SYSTEM_USER_ID:}

